apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
# CRDs from imported nemo-guardrails-controller
# Run 'make fetch-crds' to download these from GitHub
- trustyai.opendatahub.io_nemoguardrails.yaml
